package WordWarZ;


/**
* WordWarZ/_AdminServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordWarZ.idl
* Wednesday, April 23, 2025 8:37:42 PM SGT
*/


// admin operations
public class _AdminServiceStub extends org.omg.CORBA.portable.ObjectImpl implements WordWarZ.AdminService
{


  // crud
  public void createPlayer (String username, String password) throws WordWarZ.NotLoggedIn, WordWarZ.UsernameAlreadyExists
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("createPlayer", true);
                $out.write_string (username);
                $out.write_string (password);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:WordWarZ/NotLoggedIn:1.0"))
                    throw WordWarZ.NotLoggedInHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/UsernameAlreadyExists:1.0"))
                    throw WordWarZ.UsernameAlreadyExistsHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                createPlayer (username, password        );
            } finally {
                _releaseReply ($in);
            }
  } // createPlayer

  public void updatePlayer (String username, String newPassword) throws WordWarZ.NotLoggedIn, WordWarZ.PlayerNotFound, WordWarZ.PlayerCurrentlyLoggedIn
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("updatePlayer", true);
                $out.write_string (username);
                $out.write_string (newPassword);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:WordWarZ/NotLoggedIn:1.0"))
                    throw WordWarZ.NotLoggedInHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/PlayerNotFound:1.0"))
                    throw WordWarZ.PlayerNotFoundHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/PlayerCurrentlyLoggedIn:1.0"))
                    throw WordWarZ.PlayerCurrentlyLoggedInHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                updatePlayer (username, newPassword        );
            } finally {
                _releaseReply ($in);
            }
  } // updatePlayer

  public void deletePlayer (String username) throws WordWarZ.NotLoggedIn, WordWarZ.PlayerNotFound, WordWarZ.PlayerCurrentlyLoggedIn
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("deletePlayer", true);
                $out.write_string (username);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:WordWarZ/NotLoggedIn:1.0"))
                    throw WordWarZ.NotLoggedInHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/PlayerNotFound:1.0"))
                    throw WordWarZ.PlayerNotFoundHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/PlayerCurrentlyLoggedIn:1.0"))
                    throw WordWarZ.PlayerCurrentlyLoggedInHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                deletePlayer (username        );
            } finally {
                _releaseReply ($in);
            }
  } // deletePlayer

  public WordWarZ.Player getPlayer (String username) throws WordWarZ.NotLoggedIn, WordWarZ.PlayerNotFound
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getPlayer", true);
                $out.write_string (username);
                $in = _invoke ($out);
                WordWarZ.Player $result = WordWarZ.PlayerHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:WordWarZ/NotLoggedIn:1.0"))
                    throw WordWarZ.NotLoggedInHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/PlayerNotFound:1.0"))
                    throw WordWarZ.PlayerNotFoundHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getPlayer (username        );
            } finally {
                _releaseReply ($in);
            }
  } // getPlayer

  public WordWarZ.Player[] searchPlayers (String searchQuery) throws WordWarZ.NotLoggedIn, WordWarZ.PlayerNotFound
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("searchPlayers", true);
                $out.write_string (searchQuery);
                $in = _invoke ($out);
                WordWarZ.Player $result[] = WordWarZ.LeaderboardHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:WordWarZ/NotLoggedIn:1.0"))
                    throw WordWarZ.NotLoggedInHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/PlayerNotFound:1.0"))
                    throw WordWarZ.PlayerNotFoundHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return searchPlayers (searchQuery        );
            } finally {
                _releaseReply ($in);
            }
  } // searchPlayers


  // gameplay settings
  public void setGameWaitingTime (int seconds) throws WordWarZ.NotLoggedIn
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("setGameWaitingTime", true);
                $out.write_long (seconds);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:WordWarZ/NotLoggedIn:1.0"))
                    throw WordWarZ.NotLoggedInHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                setGameWaitingTime (seconds        );
            } finally {
                _releaseReply ($in);
            }
  } // setGameWaitingTime

  public void setGameRoundDuration (int seconds) throws WordWarZ.NotLoggedIn
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("setGameRoundDuration", true);
                $out.write_long (seconds);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:WordWarZ/NotLoggedIn:1.0"))
                    throw WordWarZ.NotLoggedInHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                setGameRoundDuration (seconds        );
            } finally {
                _releaseReply ($in);
            }
  } // setGameRoundDuration

  public int getGameWaitingTime () throws WordWarZ.NotLoggedIn
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getGameWaitingTime", true);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:WordWarZ/NotLoggedIn:1.0"))
                    throw WordWarZ.NotLoggedInHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getGameWaitingTime (        );
            } finally {
                _releaseReply ($in);
            }
  } // getGameWaitingTime

  public int getGameRoundDuration () throws WordWarZ.NotLoggedIn
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getGameRoundDuration", true);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:WordWarZ/NotLoggedIn:1.0"))
                    throw WordWarZ.NotLoggedInHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getGameRoundDuration (        );
            } finally {
                _releaseReply ($in);
            }
  } // getGameRoundDuration

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:WordWarZ/AdminService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "WordWarZ._AdminServiceStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _AdminServiceStub
