package WordWarZ;


/**
* WordWarZ/_GameServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/2025-9444-team6_finproject_java/src/util/idl/WordWarZ.idl
* Saturday, May 3, 2025 10:13:03 AM CST
*/


// main game
public class _GameServiceStub extends org.omg.CORBA.portable.ObjectImpl implements WordWarZ.GameService
{


  // home options
  public void startGame (String token) throws WordWarZ.NotLoggedIn, WordWarZ.NoOpponentFound
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("startGame", true);
                $out.write_string (token);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:WordWarZ/NotLoggedIn:1.0"))
                    throw WordWarZ.NotLoggedInHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/NoOpponentFound:1.0"))
                    throw WordWarZ.NoOpponentFoundHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                startGame (token        );
            } finally {
                _releaseReply ($in);
            }
  } // startGame

  public WordWarZ.Player[] getLeaderboard (String token) throws WordWarZ.NotLoggedIn
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getLeaderboard", true);
                $out.write_string (token);
                $in = _invoke ($out);
                WordWarZ.Player $result[] = WordWarZ.LeaderboardHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:WordWarZ/NotLoggedIn:1.0"))
                    throw WordWarZ.NotLoggedInHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getLeaderboard (token        );
            } finally {
                _releaseReply ($in);
            }
  } // getLeaderboard


  // queue management
  public void cancelQueue (String token) throws WordWarZ.NotLoggedIn, WordWarZ.PlayerNotInQueue
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("cancelQueue", true);
                $out.write_string (token);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:WordWarZ/NotLoggedIn:1.0"))
                    throw WordWarZ.NotLoggedInHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/PlayerNotInQueue:1.0"))
                    throw WordWarZ.PlayerNotInQueueHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                cancelQueue (token        );
            } finally {
                _releaseReply ($in);
            }
  } // cancelQueue

  public int getPlayersInQueue (String token) throws WordWarZ.NotLoggedIn, WordWarZ.PlayerNotInQueue
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getPlayersInQueue", true);
                $out.write_string (token);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:WordWarZ/NotLoggedIn:1.0"))
                    throw WordWarZ.NotLoggedInHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/PlayerNotInQueue:1.0"))
                    throw WordWarZ.PlayerNotInQueueHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getPlayersInQueue (token        );
            } finally {
                _releaseReply ($in);
            }
  } // getPlayersInQueue

  public int getTimeUntilGameStart (String token) throws WordWarZ.NotLoggedIn, WordWarZ.PlayerNotInQueue
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getTimeUntilGameStart", true);
                $out.write_string (token);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:WordWarZ/NotLoggedIn:1.0"))
                    throw WordWarZ.NotLoggedInHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/PlayerNotInQueue:1.0"))
                    throw WordWarZ.PlayerNotInQueueHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getTimeUntilGameStart (token        );
            } finally {
                _releaseReply ($in);
            }
  } // getTimeUntilGameStart


  // gameplay
  public int startRound (String token) throws WordWarZ.NotLoggedIn, WordWarZ.NotInGame, WordWarZ.GameNotFound
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("startRound", true);
                $out.write_string (token);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:WordWarZ/NotLoggedIn:1.0"))
                    throw WordWarZ.NotLoggedInHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/NotInGame:1.0"))
                    throw WordWarZ.NotInGameHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/GameNotFound:1.0"))
                    throw WordWarZ.GameNotFoundHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return startRound (token        );
            } finally {
                _releaseReply ($in);
            }
  } // startRound

  public char[] guessLetter (String token, char letter) throws WordWarZ.NotLoggedIn, WordWarZ.NotInGame, WordWarZ.GameNotFound, WordWarZ.CharacterAlreadyGuessed
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("guessLetter", true);
                $out.write_string (token);
                $out.write_char (letter);
                $in = _invoke ($out);
                char $result[] = WordWarZ.CharSequenceHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:WordWarZ/NotLoggedIn:1.0"))
                    throw WordWarZ.NotLoggedInHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/NotInGame:1.0"))
                    throw WordWarZ.NotInGameHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/GameNotFound:1.0"))
                    throw WordWarZ.GameNotFoundHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/CharacterAlreadyGuessed:1.0"))
                    throw WordWarZ.CharacterAlreadyGuessedHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return guessLetter (token, letter        );
            } finally {
                _releaseReply ($in);
            }
  } // guessLetter


  // returns char array with a placeholder for unguessed letters '_'
  public void displayWinnerByRound (String token) throws WordWarZ.NotLoggedIn, WordWarZ.NotInGame, WordWarZ.GameNotFound, WordWarZ.RoundNotFinished
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("displayWinnerByRound", true);
                $out.write_string (token);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:WordWarZ/NotLoggedIn:1.0"))
                    throw WordWarZ.NotLoggedInHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/NotInGame:1.0"))
                    throw WordWarZ.NotInGameHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/GameNotFound:1.0"))
                    throw WordWarZ.GameNotFoundHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/RoundNotFinished:1.0"))
                    throw WordWarZ.RoundNotFinishedHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                displayWinnerByRound (token        );
            } finally {
                _releaseReply ($in);
            }
  } // displayWinnerByRound

  public void displayWinnerByGame (String token) throws WordWarZ.NotLoggedIn, WordWarZ.NotInGame, WordWarZ.GameNotFound, WordWarZ.RoundNotFinished
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("displayWinnerByGame", true);
                $out.write_string (token);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:WordWarZ/NotLoggedIn:1.0"))
                    throw WordWarZ.NotLoggedInHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/NotInGame:1.0"))
                    throw WordWarZ.NotInGameHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/GameNotFound:1.0"))
                    throw WordWarZ.GameNotFoundHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/RoundNotFinished:1.0"))
                    throw WordWarZ.RoundNotFinishedHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                displayWinnerByGame (token        );
            } finally {
                _releaseReply ($in);
            }
  } // displayWinnerByGame

  public void endGame (String token) throws WordWarZ.NotLoggedIn, WordWarZ.NotInGame, WordWarZ.GameNotFound, WordWarZ.GameNotFinished
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("endGame", true);
                $out.write_string (token);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:WordWarZ/NotLoggedIn:1.0"))
                    throw WordWarZ.NotLoggedInHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/NotInGame:1.0"))
                    throw WordWarZ.NotInGameHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/GameNotFound:1.0"))
                    throw WordWarZ.GameNotFoundHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/GameNotFinished:1.0"))
                    throw WordWarZ.GameNotFinishedHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                endGame (token        );
            } finally {
                _releaseReply ($in);
            }
  } // endGame

  public String displayLoserByTime (String token) throws WordWarZ.NotLoggedIn, WordWarZ.NotInGame, WordWarZ.GameNotFound, WordWarZ.RoundNotFinished
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("displayLoserByTime", true);
                $out.write_string (token);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:WordWarZ/NotLoggedIn:1.0"))
                    throw WordWarZ.NotLoggedInHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/NotInGame:1.0"))
                    throw WordWarZ.NotInGameHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/GameNotFound:1.0"))
                    throw WordWarZ.GameNotFoundHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/RoundNotFinished:1.0"))
                    throw WordWarZ.RoundNotFinishedHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return displayLoserByTime (token        );
            } finally {
                _releaseReply ($in);
            }
  } // displayLoserByTime


  // displays the guessed word along with the user
  public String displayLoserByGuess (String token) throws WordWarZ.NotLoggedIn, WordWarZ.NotInGame, WordWarZ.GameNotFound, WordWarZ.RoundNotFinished
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("displayLoserByGuess", true);
                $out.write_string (token);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:WordWarZ/NotLoggedIn:1.0"))
                    throw WordWarZ.NotLoggedInHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/NotInGame:1.0"))
                    throw WordWarZ.NotInGameHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/GameNotFound:1.0"))
                    throw WordWarZ.GameNotFoundHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/RoundNotFinished:1.0"))
                    throw WordWarZ.RoundNotFinishedHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return displayLoserByGuess (token        );
            } finally {
                _releaseReply ($in);
            }
  } // displayLoserByGuess

  public String displayWins (String token) throws WordWarZ.NotLoggedIn, WordWarZ.NotInGame, WordWarZ.GameNotFound, WordWarZ.RoundNotFinished
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("displayWins", true);
                $out.write_string (token);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:WordWarZ/NotLoggedIn:1.0"))
                    throw WordWarZ.NotLoggedInHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/NotInGame:1.0"))
                    throw WordWarZ.NotInGameHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/GameNotFound:1.0"))
                    throw WordWarZ.GameNotFoundHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/RoundNotFinished:1.0"))
                    throw WordWarZ.RoundNotFinishedHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return displayWins (token        );
            } finally {
                _releaseReply ($in);
            }
  } // displayWins


  // game status
  public int getRemainingGuesses (String token) throws WordWarZ.NotLoggedIn, WordWarZ.NotInGame
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getRemainingGuesses", true);
                $out.write_string (token);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:WordWarZ/NotLoggedIn:1.0"))
                    throw WordWarZ.NotLoggedInHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/NotInGame:1.0"))
                    throw WordWarZ.NotInGameHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getRemainingGuesses (token        );
            } finally {
                _releaseReply ($in);
            }
  } // getRemainingGuesses

  public int getRemainingTime (String token) throws WordWarZ.NotLoggedIn, WordWarZ.NotInGame
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getRemainingTime", true);
                $out.write_string (token);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:WordWarZ/NotLoggedIn:1.0"))
                    throw WordWarZ.NotLoggedInHelper.read ($in);
                else if (_id.equals ("IDL:WordWarZ/NotInGame:1.0"))
                    throw WordWarZ.NotInGameHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getRemainingTime (token        );
            } finally {
                _releaseReply ($in);
            }
  } // getRemainingTime


  // callbacks
  public void registerCallback (String token, WordWarZ.ClientCallback callback) throws WordWarZ.NotLoggedIn
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registerCallback", true);
                $out.write_string (token);
                WordWarZ.ClientCallbackHelper.write ($out, callback);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:WordWarZ/NotLoggedIn:1.0"))
                    throw WordWarZ.NotLoggedInHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registerCallback (token, callback        );
            } finally {
                _releaseReply ($in);
            }
  } // registerCallback

  public void unregisterCallback (String token) throws WordWarZ.NotLoggedIn
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("unregisterCallback", true);
                $out.write_string (token);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:WordWarZ/NotLoggedIn:1.0"))
                    throw WordWarZ.NotLoggedInHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                unregisterCallback (token        );
            } finally {
                _releaseReply ($in);
            }
  } // unregisterCallback

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:WordWarZ/GameService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "WordWarZ._GameServiceStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _GameServiceStub
