package WordWarZ;


/**
* WordWarZ/AdminService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordWarZ.idl
* Saturday, April 26, 2025 8:20:14 AM SGT
*/


// admin operations
public interface AdminService extends AdminServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AdminService
