package WordWarZ;

/**
* WordWarZ/AdminServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/frances/2025-9444-team6_finproject_java/WordWarZ.idl
* Saturday, May 3, 2025 8:13:31 AM CST
*/


// admin operations
public final class AdminServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public WordWarZ.AdminService value = null;

  public AdminServiceHolder ()
  {
  }

  public AdminServiceHolder (WordWarZ.AdminService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordWarZ.AdminServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordWarZ.AdminServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordWarZ.AdminServiceHelper.type ();
  }

}
