package WordWarZ;


/**
* WordWarZ/AdminServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordWarZ.idl
* Wednesday, April 23, 2025 8:37:42 PM SGT
*/


// admin operations
public abstract class AdminServicePOA extends org.omg.PortableServer.Servant
 implements WordWarZ.AdminServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createPlayer", new java.lang.Integer (0));
    _methods.put ("updatePlayer", new java.lang.Integer (1));
    _methods.put ("deletePlayer", new java.lang.Integer (2));
    _methods.put ("getPlayer", new java.lang.Integer (3));
    _methods.put ("searchPlayers", new java.lang.Integer (4));
    _methods.put ("setGameWaitingTime", new java.lang.Integer (5));
    _methods.put ("setGameRoundDuration", new java.lang.Integer (6));
    _methods.put ("getGameWaitingTime", new java.lang.Integer (7));
    _methods.put ("getGameRoundDuration", new java.lang.Integer (8));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // crud
       case 0:  // WordWarZ/AdminService/createPlayer
       {
         try {
           String username = in.read_string ();
           String password = in.read_string ();
           this.createPlayer (username, password);
           out = $rh.createReply();
         } catch (WordWarZ.NotLoggedIn $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotLoggedInHelper.write (out, $ex);
         } catch (WordWarZ.UsernameAlreadyExists $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.UsernameAlreadyExistsHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // WordWarZ/AdminService/updatePlayer
       {
         try {
           String username = in.read_string ();
           String newPassword = in.read_string ();
           this.updatePlayer (username, newPassword);
           out = $rh.createReply();
         } catch (WordWarZ.NotLoggedIn $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotLoggedInHelper.write (out, $ex);
         } catch (WordWarZ.PlayerNotFound $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.PlayerNotFoundHelper.write (out, $ex);
         } catch (WordWarZ.PlayerCurrentlyLoggedIn $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.PlayerCurrentlyLoggedInHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // WordWarZ/AdminService/deletePlayer
       {
         try {
           String username = in.read_string ();
           this.deletePlayer (username);
           out = $rh.createReply();
         } catch (WordWarZ.NotLoggedIn $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotLoggedInHelper.write (out, $ex);
         } catch (WordWarZ.PlayerNotFound $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.PlayerNotFoundHelper.write (out, $ex);
         } catch (WordWarZ.PlayerCurrentlyLoggedIn $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.PlayerCurrentlyLoggedInHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // WordWarZ/AdminService/getPlayer
       {
         try {
           String username = in.read_string ();
           WordWarZ.Player $result = null;
           $result = this.getPlayer (username);
           out = $rh.createReply();
           WordWarZ.PlayerHelper.write (out, $result);
         } catch (WordWarZ.NotLoggedIn $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotLoggedInHelper.write (out, $ex);
         } catch (WordWarZ.PlayerNotFound $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.PlayerNotFoundHelper.write (out, $ex);
         }
         break;
       }

       case 4:  // WordWarZ/AdminService/searchPlayers
       {
         try {
           String searchQuery = in.read_string ();
           WordWarZ.Player $result[] = null;
           $result = this.searchPlayers (searchQuery);
           out = $rh.createReply();
           WordWarZ.LeaderboardHelper.write (out, $result);
         } catch (WordWarZ.NotLoggedIn $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotLoggedInHelper.write (out, $ex);
         } catch (WordWarZ.PlayerNotFound $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.PlayerNotFoundHelper.write (out, $ex);
         }
         break;
       }


  // gameplay settings
       case 5:  // WordWarZ/AdminService/setGameWaitingTime
       {
         try {
           int seconds = in.read_long ();
           this.setGameWaitingTime (seconds);
           out = $rh.createReply();
         } catch (WordWarZ.NotLoggedIn $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotLoggedInHelper.write (out, $ex);
         }
         break;
       }

       case 6:  // WordWarZ/AdminService/setGameRoundDuration
       {
         try {
           int seconds = in.read_long ();
           this.setGameRoundDuration (seconds);
           out = $rh.createReply();
         } catch (WordWarZ.NotLoggedIn $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotLoggedInHelper.write (out, $ex);
         }
         break;
       }

       case 7:  // WordWarZ/AdminService/getGameWaitingTime
       {
         try {
           int $result = (int)0;
           $result = this.getGameWaitingTime ();
           out = $rh.createReply();
           out.write_long ($result);
         } catch (WordWarZ.NotLoggedIn $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotLoggedInHelper.write (out, $ex);
         }
         break;
       }

       case 8:  // WordWarZ/AdminService/getGameRoundDuration
       {
         try {
           int $result = (int)0;
           $result = this.getGameRoundDuration ();
           out = $rh.createReply();
           out.write_long ($result);
         } catch (WordWarZ.NotLoggedIn $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotLoggedInHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:WordWarZ/AdminService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public AdminService _this() 
  {
    return AdminServiceHelper.narrow(
    super._this_object());
  }

  public AdminService _this(org.omg.CORBA.ORB orb) 
  {
    return AdminServiceHelper.narrow(
    super._this_object(orb));
  }


} // class AdminServicePOA
