package WordWarZ;


/**
* WordWarZ/AdminServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordWarZ.idl
* Wednesday, April 23, 2025 8:37:42 PM SGT
*/


// admin operations
public interface AdminServiceOperations 
{

  // crud
  void createPlayer (String username, String password) throws WordWarZ.NotLoggedIn, WordWarZ.UsernameAlreadyExists;
  void updatePlayer (String username, String newPassword) throws WordWarZ.NotLoggedIn, WordWarZ.PlayerNotFound, WordWarZ.PlayerCurrentlyLoggedIn;
  void deletePlayer (String username) throws WordWarZ.NotLoggedIn, WordWarZ.PlayerNotFound, WordWarZ.PlayerCurrentlyLoggedIn;
  WordWarZ.Player getPlayer (String username) throws WordWarZ.NotLoggedIn, WordWarZ.PlayerNotFound;
  WordWarZ.Player[] searchPlayers (String searchQuery) throws WordWarZ.NotLoggedIn, WordWarZ.PlayerNotFound;

  // gameplay settings
  void setGameWaitingTime (int seconds) throws WordWarZ.NotLoggedIn;
  void setGameRoundDuration (int seconds) throws WordWarZ.NotLoggedIn;
  int getGameWaitingTime () throws WordWarZ.NotLoggedIn;
  int getGameRoundDuration () throws WordWarZ.NotLoggedIn;
} // interface AdminServiceOperations
