package WordWarZ;


/**
* WordWarZ/AlreadyLoggedIn.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordWarZ.idl
* Wednesday, April 23, 2025 8:37:42 PM SGT
*/

public final class AlreadyLoggedIn extends org.omg.CORBA.UserException
{

  public AlreadyLoggedIn ()
  {
    super(AlreadyLoggedInHelper.id());
  } // ctor


  public AlreadyLoggedIn (String $reason)
  {
    super(AlreadyLoggedInHelper.id() + "  " + $reason);
  } // ctor

} // class AlreadyLoggedIn
