package WordWarZ;


/**
* WordWarZ/CharSequenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Thursday, May 15, 2025 2:57:41 PM SGT
*/

public final class CharSequenceHolder implements org.omg.CORBA.portable.Streamable
{
  public char value[] = null;

  public CharSequenceHolder ()
  {
  }

  public CharSequenceHolder (char[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordWarZ.CharSequenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordWarZ.CharSequenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordWarZ.CharSequenceHelper.type ();
  }

}
