package WordWarZ;


/**
* WordWarZ/CharacterAlreadyGuessed.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/2025-9444-team6_finproject_java/src/util/idl/WordWarZ.idl
* Saturday, May 3, 2025 10:13:03 AM CST
*/

public final class CharacterAlreadyGuessed extends org.omg.CORBA.UserException
{
  public String reason = null;

  public CharacterAlreadyGuessed ()
  {
    super(CharacterAlreadyGuessedHelper.id());
  } // ctor

  public CharacterAlreadyGuessed (String _reason)
  {
    super(CharacterAlreadyGuessedHelper.id());
    reason = _reason;
  } // ctor


  public CharacterAlreadyGuessed (String $reason, String _reason)
  {
    super(CharacterAlreadyGuessedHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class CharacterAlreadyGuessed
