package WordWarZ;


/**
* WordWarZ/CharacterAlreadyGuessed.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordWarZ.idl
* Saturday, April 26, 2025 8:20:14 AM SGT
*/

public final class CharacterAlreadyGuessed extends org.omg.CORBA.UserException
{

  public CharacterAlreadyGuessed ()
  {
    super(CharacterAlreadyGuessedHelper.id());
  } // ctor


  public CharacterAlreadyGuessed (String $reason)
  {
    super(CharacterAlreadyGuessedHelper.id() + "  " + $reason);
  } // ctor

} // class CharacterAlreadyGuessed
