package WordWarZ;


/**
* WordWarZ/CharacterAlreadyGuessed.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Sunday, May 11, 2025 5:49:02 PM SGT
*/

public final class CharacterAlreadyGuessed extends org.omg.CORBA.UserException
{
  public String reason = null;

  public CharacterAlreadyGuessed ()
  {
    super(CharacterAlreadyGuessedHelper.id());
  } // ctor

  public CharacterAlreadyGuessed (String _reason)
  {
    super(CharacterAlreadyGuessedHelper.id());
    reason = _reason;
  } // ctor


  public CharacterAlreadyGuessed (String $reason, String _reason)
  {
    super(CharacterAlreadyGuessedHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class CharacterAlreadyGuessed
