package WordWarZ;

/**
* WordWarZ/CharacterAlreadyGuessedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Monday, May 5, 2025 10:03:03 PM SGT
*/

public final class CharacterAlreadyGuessedHolder implements org.omg.CORBA.portable.Streamable
{
  public WordWarZ.CharacterAlreadyGuessed value = null;

  public CharacterAlreadyGuessedHolder ()
  {
  }

  public CharacterAlreadyGuessedHolder (WordWarZ.CharacterAlreadyGuessed initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordWarZ.CharacterAlreadyGuessedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordWarZ.CharacterAlreadyGuessedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordWarZ.CharacterAlreadyGuessedHelper.type ();
  }

}
