package WordWarZ;

/**
* WordWarZ/CharacterAlreadyGuessedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Thursday, May 15, 2025 2:57:41 PM SGT
*/

public final class CharacterAlreadyGuessedHolder implements org.omg.CORBA.portable.Streamable
{
  public WordWarZ.CharacterAlreadyGuessed value = null;

  public CharacterAlreadyGuessedHolder ()
  {
  }

  public CharacterAlreadyGuessedHolder (WordWarZ.CharacterAlreadyGuessed initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordWarZ.CharacterAlreadyGuessedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordWarZ.CharacterAlreadyGuessedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordWarZ.CharacterAlreadyGuessedHelper.type ();
  }

}
