package WordWarZ;


/**
* WordWarZ/ClientCallbackPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Thursday, May 15, 2025 2:57:41 PM SGT
*/


// client-side interface callbacks
public abstract class ClientCallbackPOA extends org.omg.PortableServer.Servant
 implements WordWarZ.ClientCallbackOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("onQueueUpdated", new java.lang.Integer (0));
    _methods.put ("onGameCountdown", new java.lang.Integer (1));
    _methods.put ("onRoundStarted", new java.lang.Integer (2));
    _methods.put ("onRoundLost", new java.lang.Integer (3));
    _methods.put ("onRoundWon", new java.lang.Integer (4));
    _methods.put ("onRoundDrawn", new java.lang.Integer (5));
    _methods.put ("onGameLost", new java.lang.Integer (6));
    _methods.put ("onGameWon", new java.lang.Integer (7));
    _methods.put ("onForceLogout", new java.lang.Integer (8));
    _methods.put ("onPlayerDisconnected", new java.lang.Integer (9));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // WordWarZ/ClientCallback/onQueueUpdated
       {
         int playerCount = in.read_long ();
         this.onQueueUpdated (playerCount);
         out = $rh.createReply();
         break;
       }

       case 1:  // WordWarZ/ClientCallback/onGameCountdown
       {
         int secondsLeft = in.read_long ();
         this.onGameCountdown (secondsLeft);
         out = $rh.createReply();
         break;
       }

       case 2:  // WordWarZ/ClientCallback/onRoundStarted
       {
         char wordPlaceholder[] = WordWarZ.CharSequenceHelper.read (in);
         this.onRoundStarted (wordPlaceholder);
         out = $rh.createReply();
         break;
       }

       case 3:  // WordWarZ/ClientCallback/onRoundLost
       {
         String word = in.read_string ();
         String winner = in.read_string ();
         this.onRoundLost (word, winner);
         out = $rh.createReply();
         break;
       }

       case 4:  // WordWarZ/ClientCallback/onRoundWon
       {
         String word = in.read_string ();
         this.onRoundWon (word);
         out = $rh.createReply();
         break;
       }

       case 5:  // WordWarZ/ClientCallback/onRoundDrawn
       {
         String word = in.read_string ();
         this.onRoundDrawn (word);
         out = $rh.createReply();
         break;
       }

       case 6:  // WordWarZ/ClientCallback/onGameLost
       {
         String winnerUsername = in.read_string ();
         this.onGameLost (winnerUsername);
         out = $rh.createReply();
         break;
       }

       case 7:  // WordWarZ/ClientCallback/onGameWon
       {
         String winnerUsername = in.read_string ();
         this.onGameWon (winnerUsername);
         out = $rh.createReply();
         break;
       }

       case 8:  // WordWarZ/ClientCallback/onForceLogout
       {
         this.onForceLogout ();
         out = $rh.createReply();
         break;
       }

       case 9:  // WordWarZ/ClientCallback/onPlayerDisconnected
       {
         String username = in.read_string ();
         this.onPlayerDisconnected (username);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:WordWarZ/ClientCallback:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ClientCallback _this() 
  {
    return ClientCallbackHelper.narrow(
    super._this_object());
  }

  public ClientCallback _this(org.omg.CORBA.ORB orb) 
  {
    return ClientCallbackHelper.narrow(
    super._this_object(orb));
  }


} // class ClientCallbackPOA
