package WordWarZ;


/**
* WordWarZ/ClientCallback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/frances/2025-9444-team6_finproject_java/src/GameService.idl
* Monday, May 5, 2025 10:08:28 PM CST
*/


// client-side interface callbacks
public interface ClientCallback extends ClientCallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClientCallback
