package WordWarZ;


/**
* WordWarZ/ClientCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Monday, May 5, 2025 10:03:03 PM SGT
*/


// client-side interface callbacks
public interface ClientCallbackOperations 
{
  void onQueueUpdated (int playerCount);
  void onLeaderboardUpdated (WordWarZ.Player[] leaderboard);
  void onGameCountdown (int secondsLeft);
  void onRoundStarted (String[] wordPlaceholder);
  void onRoundLost (String word, String winner);
  void onRoundWon (String word);
  void onRoundDrawn (String word);
  void onGameLost (String winnerUsername);
  void onGameWon (String winnerUsername);
  void onForceLogout ();
} // interface ClientCallbackOperations
