package WordWarZ;


/**
* WordWarZ/ClientCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordWarZ.idl
* Wednesday, April 23, 2025 8:37:42 PM SGT
*/


// client-side interface callbacks
public interface ClientCallbackOperations 
{
  void onQueueUpdated (int playerCount);
  void onLeaderboardUpdated (WordWarZ.Player[] leaderboard);
  void onGameCountdown (int secondsLeft);

  // maybe called every second
  void onRoundStarted (String[] wordPlaceholder);
  void onRoundEnded (String roundResult, String winner);
  void onGameEnded (String winnerUsername);
} // interface ClientCallbackOperations
