package WordWarZ;


/**
* WordWarZ/ClientCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/2025-9444-team6_finproject_java/src/util/idl/WordWarZ.idl
* Saturday, May 3, 2025 10:13:03 AM CST
*/


// client-side interface callbacks
public interface ClientCallbackOperations 
{
  void onQueueUpdated (int playerCount);
  void onLeaderboardUpdated (WordWarZ.Player[] leaderboard);
  void onGameCountdown (int secondsLeft);

  // maybe called every second
  void onRoundStarted (String[] wordPlaceholder);
  void onRoundEnded (String roundResult, String winner);
  void onGameEnded (String winnerUsername);
  void onForceLogout ();
} // interface ClientCallbackOperations
