package WordWarZ;


/**
* WordWarZ/ClientCallbackPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/2025-9444-team6_finproject_java/src/util/idl/WordWarZ.idl
* Saturday, May 3, 2025 10:13:03 AM CST
*/


// client-side interface callbacks
public abstract class ClientCallbackPOA extends org.omg.PortableServer.Servant
 implements WordWarZ.ClientCallbackOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("onQueueUpdated", new java.lang.Integer (0));
    _methods.put ("onLeaderboardUpdated", new java.lang.Integer (1));
    _methods.put ("onGameCountdown", new java.lang.Integer (2));
    _methods.put ("onRoundStarted", new java.lang.Integer (3));
    _methods.put ("onRoundEnded", new java.lang.Integer (4));
    _methods.put ("onGameEnded", new java.lang.Integer (5));
    _methods.put ("onForceLogout", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // WordWarZ/ClientCallback/onQueueUpdated
       {
         int playerCount = in.read_long ();
         this.onQueueUpdated (playerCount);
         out = $rh.createReply();
         break;
       }

       case 1:  // WordWarZ/ClientCallback/onLeaderboardUpdated
       {
         WordWarZ.Player leaderboard[] = WordWarZ.LeaderboardHelper.read (in);
         this.onLeaderboardUpdated (leaderboard);
         out = $rh.createReply();
         break;
       }

       case 2:  // WordWarZ/ClientCallback/onGameCountdown
       {
         int secondsLeft = in.read_long ();
         this.onGameCountdown (secondsLeft);
         out = $rh.createReply();
         break;
       }


  // maybe called every second
       case 3:  // WordWarZ/ClientCallback/onRoundStarted
       {
         String wordPlaceholder[] = WordWarZ.StringSequenceHelper.read (in);
         this.onRoundStarted (wordPlaceholder);
         out = $rh.createReply();
         break;
       }

       case 4:  // WordWarZ/ClientCallback/onRoundEnded
       {
         String roundResult = in.read_string ();
         String winner = in.read_string ();
         this.onRoundEnded (roundResult, winner);
         out = $rh.createReply();
         break;
       }

       case 5:  // WordWarZ/ClientCallback/onGameEnded
       {
         String winnerUsername = in.read_string ();
         this.onGameEnded (winnerUsername);
         out = $rh.createReply();
         break;
       }

       case 6:  // WordWarZ/ClientCallback/onForceLogout
       {
         this.onForceLogout ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:WordWarZ/ClientCallback:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ClientCallback _this() 
  {
    return ClientCallbackHelper.narrow(
    super._this_object());
  }

  public ClientCallback _this(org.omg.CORBA.ORB orb) 
  {
    return ClientCallbackHelper.narrow(
    super._this_object(orb));
  }


} // class ClientCallbackPOA
