package WordWarZ;


/**
* WordWarZ/GameNotFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/2025-9444-team6_finproject_java/src/util/idl/WordWarZ.idl
* Saturday, May 3, 2025 10:13:03 AM CST
*/

public final class GameNotFound extends org.omg.CORBA.UserException
{
  public String reason = null;

  public GameNotFound ()
  {
    super(GameNotFoundHelper.id());
  } // ctor

  public GameNotFound (String _reason)
  {
    super(GameNotFoundHelper.id());
    reason = _reason;
  } // ctor


  public GameNotFound (String $reason, String _reason)
  {
    super(GameNotFoundHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class GameNotFound
