package WordWarZ;


/**
* WordWarZ/GameServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/2025-9444-team6_finproject_java/src/util/idl/WordWarZ.idl
* Saturday, May 3, 2025 10:13:03 AM CST
*/


// main game
public interface GameServiceOperations 
{

  // home options
  void startGame (String token) throws WordWarZ.NotLoggedIn, WordWarZ.NoOpponentFound;
  WordWarZ.Player[] getLeaderboard (String token) throws WordWarZ.NotLoggedIn;

  // queue management
  void cancelQueue (String token) throws WordWarZ.NotLoggedIn, WordWarZ.PlayerNotInQueue;
  int getPlayersInQueue (String token) throws WordWarZ.NotLoggedIn, WordWarZ.PlayerNotInQueue;
  int getTimeUntilGameStart (String token) throws WordWarZ.NotLoggedIn, WordWarZ.PlayerNotInQueue;

  // gameplay
  int startRound (String token) throws WordWarZ.NotLoggedIn, WordWarZ.NotInGame, WordWarZ.GameNotFound;
  char[] guessLetter (String token, char letter) throws WordWarZ.NotLoggedIn, WordWarZ.NotInGame, WordWarZ.GameNotFound, WordWarZ.CharacterAlreadyGuessed;

  // returns char array with a placeholder for unguessed letters '_'
  void displayWinnerByRound (String token) throws WordWarZ.NotLoggedIn, WordWarZ.NotInGame, WordWarZ.GameNotFound, WordWarZ.RoundNotFinished;
  void displayWinnerByGame (String token) throws WordWarZ.NotLoggedIn, WordWarZ.NotInGame, WordWarZ.GameNotFound, WordWarZ.RoundNotFinished;
  void endGame (String token) throws WordWarZ.NotLoggedIn, WordWarZ.NotInGame, WordWarZ.GameNotFound, WordWarZ.GameNotFinished;
  String displayLoserByTime (String token) throws WordWarZ.NotLoggedIn, WordWarZ.NotInGame, WordWarZ.GameNotFound, WordWarZ.RoundNotFinished;

  // displays the guessed word along with the user
  String displayLoserByGuess (String token) throws WordWarZ.NotLoggedIn, WordWarZ.NotInGame, WordWarZ.GameNotFound, WordWarZ.RoundNotFinished;
  String displayWins (String token) throws WordWarZ.NotLoggedIn, WordWarZ.NotInGame, WordWarZ.GameNotFound, WordWarZ.RoundNotFinished;

  // game status
  int getRemainingGuesses (String token) throws WordWarZ.NotLoggedIn, WordWarZ.NotInGame;
  int getRemainingTime (String token) throws WordWarZ.NotLoggedIn, WordWarZ.NotInGame;

  // callbacks
  void registerCallback (String token, WordWarZ.ClientCallback callback) throws WordWarZ.NotLoggedIn;
  void unregisterCallback (String token) throws WordWarZ.NotLoggedIn;
} // interface GameServiceOperations
