package WordWarZ;


/**
* WordWarZ/GameServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Thursday, May 15, 2025 2:57:41 PM SGT
*/


// main game
public abstract class GameServicePOA extends org.omg.PortableServer.Servant
 implements WordWarZ.GameServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("startGame", new java.lang.Integer (0));
    _methods.put ("getLeaderboard", new java.lang.Integer (1));
    _methods.put ("cancelQueue", new java.lang.Integer (2));
    _methods.put ("getPlayersInQueue", new java.lang.Integer (3));
    _methods.put ("getTimeUntilGameStart", new java.lang.Integer (4));
    _methods.put ("startRound", new java.lang.Integer (5));
    _methods.put ("getRoundDuration", new java.lang.Integer (6));
    _methods.put ("guessLetter", new java.lang.Integer (7));
    _methods.put ("endRound", new java.lang.Integer (8));
    _methods.put ("notifyPlayerLost", new java.lang.Integer (9));
    _methods.put ("endGame", new java.lang.Integer (10));
    _methods.put ("displayWins", new java.lang.Integer (11));
    _methods.put ("registerCallback", new java.lang.Integer (12));
    _methods.put ("unregisterCallback", new java.lang.Integer (13));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // home options
       case 0:  // WordWarZ/GameService/startGame
       {
         try {
           String token = in.read_string ();
           this.startGame (token);
           out = $rh.createReply();
         } catch (WordWarZ.NotLoggedIn $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotLoggedInHelper.write (out, $ex);
         } catch (WordWarZ.NoOpponentFound $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NoOpponentFoundHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // WordWarZ/GameService/getLeaderboard
       {
         try {
           String token = in.read_string ();
           WordWarZ.Player $result[] = null;
           $result = this.getLeaderboard (token);
           out = $rh.createReply();
           WordWarZ.LeaderboardHelper.write (out, $result);
         } catch (WordWarZ.NotLoggedIn $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotLoggedInHelper.write (out, $ex);
         }
         break;
       }


  // queue management
       case 2:  // WordWarZ/GameService/cancelQueue
       {
         try {
           String token = in.read_string ();
           this.cancelQueue (token);
           out = $rh.createReply();
         } catch (WordWarZ.NotLoggedIn $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotLoggedInHelper.write (out, $ex);
         } catch (WordWarZ.PlayerNotInQueue $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.PlayerNotInQueueHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // WordWarZ/GameService/getPlayersInQueue
       {
         try {
           String token = in.read_string ();
           int $result = (int)0;
           $result = this.getPlayersInQueue (token);
           out = $rh.createReply();
           out.write_long ($result);
         } catch (WordWarZ.NotLoggedIn $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotLoggedInHelper.write (out, $ex);
         } catch (WordWarZ.PlayerNotInQueue $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.PlayerNotInQueueHelper.write (out, $ex);
         }
         break;
       }

       case 4:  // WordWarZ/GameService/getTimeUntilGameStart
       {
         try {
           String token = in.read_string ();
           int $result = (int)0;
           $result = this.getTimeUntilGameStart (token);
           out = $rh.createReply();
           out.write_long ($result);
         } catch (WordWarZ.NotLoggedIn $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotLoggedInHelper.write (out, $ex);
         } catch (WordWarZ.PlayerNotInQueue $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.PlayerNotInQueueHelper.write (out, $ex);
         }
         break;
       }


  // gameplay
       case 5:  // WordWarZ/GameService/startRound
       {
         try {
           String token = in.read_string ();
           int $result = (int)0;
           $result = this.startRound (token);
           out = $rh.createReply();
           out.write_long ($result);
         } catch (WordWarZ.NotLoggedIn $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotLoggedInHelper.write (out, $ex);
         } catch (WordWarZ.NotInGame $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotInGameHelper.write (out, $ex);
         } catch (WordWarZ.GameNotFound $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.GameNotFoundHelper.write (out, $ex);
         }
         break;
       }

       case 6:  // WordWarZ/GameService/getRoundDuration
       {
         try {
           String token = in.read_string ();
           int $result = (int)0;
           $result = this.getRoundDuration (token);
           out = $rh.createReply();
           out.write_long ($result);
         } catch (WordWarZ.NotLoggedIn $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotLoggedInHelper.write (out, $ex);
         } catch (WordWarZ.NotInGame $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotInGameHelper.write (out, $ex);
         } catch (WordWarZ.GameNotFound $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.GameNotFoundHelper.write (out, $ex);
         }
         break;
       }

       case 7:  // WordWarZ/GameService/guessLetter
       {
         try {
           String token = in.read_string ();
           char letter = in.read_char ();
           char $result[] = null;
           $result = this.guessLetter (token, letter);
           out = $rh.createReply();
           WordWarZ.CharSequenceHelper.write (out, $result);
         } catch (WordWarZ.NotLoggedIn $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotLoggedInHelper.write (out, $ex);
         } catch (WordWarZ.NotInGame $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotInGameHelper.write (out, $ex);
         } catch (WordWarZ.GameNotFound $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.GameNotFoundHelper.write (out, $ex);
         } catch (WordWarZ.CharacterAlreadyGuessed $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.CharacterAlreadyGuessedHelper.write (out, $ex);
         }
         break;
       }


  // returns char array with a placeholder for unguessed letters '_'
       case 8:  // WordWarZ/GameService/endRound
       {
         try {
           String token = in.read_string ();
           this.endRound (token);
           out = $rh.createReply();
         } catch (WordWarZ.NotLoggedIn $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotLoggedInHelper.write (out, $ex);
         } catch (WordWarZ.NotInGame $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotInGameHelper.write (out, $ex);
         } catch (WordWarZ.GameNotFound $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.GameNotFoundHelper.write (out, $ex);
         }
         break;
       }

       case 9:  // WordWarZ/GameService/notifyPlayerLost
       {
         try {
           String token = in.read_string ();
           this.notifyPlayerLost (token);
           out = $rh.createReply();
         } catch (WordWarZ.NotLoggedIn $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotLoggedInHelper.write (out, $ex);
         } catch (WordWarZ.NotInGame $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotInGameHelper.write (out, $ex);
         } catch (WordWarZ.GameNotFound $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.GameNotFoundHelper.write (out, $ex);
         }
         break;
       }

       case 10:  // WordWarZ/GameService/endGame
       {
         try {
           String token = in.read_string ();
           this.endGame (token);
           out = $rh.createReply();
         } catch (WordWarZ.NotLoggedIn $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotLoggedInHelper.write (out, $ex);
         } catch (WordWarZ.NotInGame $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotInGameHelper.write (out, $ex);
         } catch (WordWarZ.GameNotFound $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.GameNotFoundHelper.write (out, $ex);
         } catch (WordWarZ.GameNotFinished $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.GameNotFinishedHelper.write (out, $ex);
         }
         break;
       }

       case 11:  // WordWarZ/GameService/displayWins
       {
         try {
           String token = in.read_string ();
           int $result = (int)0;
           $result = this.displayWins (token);
           out = $rh.createReply();
           out.write_long ($result);
         } catch (WordWarZ.NotLoggedIn $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotLoggedInHelper.write (out, $ex);
         } catch (WordWarZ.NotInGame $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotInGameHelper.write (out, $ex);
         } catch (WordWarZ.GameNotFound $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.GameNotFoundHelper.write (out, $ex);
         } catch (WordWarZ.RoundNotFinished $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.RoundNotFinishedHelper.write (out, $ex);
         }
         break;
       }


  // callbacks
       case 12:  // WordWarZ/GameService/registerCallback
       {
         try {
           String token = in.read_string ();
           WordWarZ.ClientCallback callback = WordWarZ.ClientCallbackHelper.read (in);
           this.registerCallback (token, callback);
           out = $rh.createReply();
         } catch (WordWarZ.NotLoggedIn $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotLoggedInHelper.write (out, $ex);
         }
         break;
       }

       case 13:  // WordWarZ/GameService/unregisterCallback
       {
         try {
           String token = in.read_string ();
           this.unregisterCallback (token);
           out = $rh.createReply();
         } catch (WordWarZ.NotLoggedIn $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotLoggedInHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:WordWarZ/GameService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GameService _this() 
  {
    return GameServiceHelper.narrow(
    super._this_object());
  }

  public GameService _this(org.omg.CORBA.ORB orb) 
  {
    return GameServiceHelper.narrow(
    super._this_object(orb));
  }


} // class GameServicePOA
