package WordWarZ;


/**
* WordWarZ/GameNotFinished.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordWarZ.idl
* Wednesday, April 23, 2025 8:37:42 PM SGT
*/

public final class GameNotFinished extends org.omg.CORBA.UserException
{

  public GameNotFinished ()
  {
    super(GameNotFinishedHelper.id());
  } // ctor


  public GameNotFinished (String $reason)
  {
    super(GameNotFinishedHelper.id() + "  " + $reason);
  } // ctor

} // class GameNotFinished
