package WordWarZ;

/**
* WordWarZ/GameNotFinishedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Monday, May 12, 2025 7:37:02 PM SGT
*/

public final class GameNotFinishedHolder implements org.omg.CORBA.portable.Streamable
{
  public WordWarZ.GameNotFinished value = null;

  public GameNotFinishedHolder ()
  {
  }

  public GameNotFinishedHolder (WordWarZ.GameNotFinished initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordWarZ.GameNotFinishedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordWarZ.GameNotFinishedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordWarZ.GameNotFinishedHelper.type ();
  }

}
