package WordWarZ;


/**
* WordWarZ/GameNotFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Wednesday, May 7, 2025 1:44:57 AM SGT
*/

public final class GameNotFound extends org.omg.CORBA.UserException
{
  public String reason = null;

  public GameNotFound ()
  {
    super(GameNotFoundHelper.id());
  } // ctor

  public GameNotFound (String _reason)
  {
    super(GameNotFoundHelper.id());
    reason = _reason;
  } // ctor


  public GameNotFound (String $reason, String _reason)
  {
    super(GameNotFoundHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class GameNotFound
