package WordWarZ;


/**
* WordWarZ/GameNotFinished.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Monday, May 12, 2025 7:37:02 PM SGT
*/

public final class GameNotFinished extends org.omg.CORBA.UserException
{
  public String reason = null;

  public GameNotFinished ()
  {
    super(GameNotFinishedHelper.id());
  } // ctor

  public GameNotFinished (String _reason)
  {
    super(GameNotFinishedHelper.id());
    reason = _reason;
  } // ctor


  public GameNotFinished (String $reason, String _reason)
  {
    super(GameNotFinishedHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class GameNotFinished
