package WordWarZ;


/**
* WordWarZ/GameNotFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordWarZ.idl
* Wednesday, April 23, 2025 8:37:42 PM SGT
*/

public final class GameNotFound extends org.omg.CORBA.UserException
{

  public GameNotFound ()
  {
    super(GameNotFoundHelper.id());
  } // ctor


  public GameNotFound (String $reason)
  {
    super(GameNotFoundHelper.id() + "  " + $reason);
  } // ctor

} // class GameNotFound
