package WordWarZ;


/**
* WordWarZ/GameService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Thursday, May 15, 2025 2:57:41 PM SGT
*/


// main game
public interface GameService extends GameServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GameService
