package WordWarZ;

/**
* WordWarZ/GameServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordWarZ.idl
* Saturday, April 26, 2025 8:20:14 AM SGT
*/


// main game
public final class GameServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public WordWarZ.GameService value = null;

  public GameServiceHolder ()
  {
  }

  public GameServiceHolder (WordWarZ.GameService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordWarZ.GameServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordWarZ.GameServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordWarZ.GameServiceHelper.type ();
  }

}
