package WordWarZ;


/**
* WordWarZ/GameServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Monday, May 12, 2025 7:37:02 PM SGT
*/


// main game
public interface GameServiceOperations 
{

  // home options
  void startGame (String token) throws WordWarZ.NotLoggedIn, WordWarZ.NoOpponentFound;
  WordWarZ.Player[] getLeaderboard (String token) throws WordWarZ.NotLoggedIn;

  // queue management
  void cancelQueue (String token) throws WordWarZ.NotLoggedIn, WordWarZ.PlayerNotInQueue;
  int getPlayersInQueue (String token) throws WordWarZ.NotLoggedIn, WordWarZ.PlayerNotInQueue;
  int getTimeUntilGameStart (String token) throws WordWarZ.NotLoggedIn, WordWarZ.PlayerNotInQueue;

  // gameplay
  int startRound (String token) throws WordWarZ.NotLoggedIn, WordWarZ.NotInGame, WordWarZ.GameNotFound;
  int getRoundDuration (String token) throws WordWarZ.NotLoggedIn, WordWarZ.NotInGame, WordWarZ.GameNotFound;
  char[] guessLetter (String token, char letter) throws WordWarZ.NotLoggedIn, WordWarZ.NotInGame, WordWarZ.GameNotFound, WordWarZ.CharacterAlreadyGuessed;

  // returns char array with a placeholder for unguessed letters '_'
  void endRound (String token) throws WordWarZ.NotLoggedIn, WordWarZ.NotInGame, WordWarZ.GameNotFound;
  void notifyPlayerLost (String token) throws WordWarZ.NotLoggedIn, WordWarZ.NotInGame, WordWarZ.GameNotFound;
  void endGame (String token) throws WordWarZ.NotLoggedIn, WordWarZ.NotInGame, WordWarZ.GameNotFound, WordWarZ.GameNotFinished;
  String displayWins (String token) throws WordWarZ.NotLoggedIn, WordWarZ.NotInGame, WordWarZ.GameNotFound, WordWarZ.RoundNotFinished;

  // callbacks
  void registerCallback (String token, WordWarZ.ClientCallback callback) throws WordWarZ.NotLoggedIn;
  void unregisterCallback (String token) throws WordWarZ.NotLoggedIn;
} // interface GameServiceOperations
