package WordWarZ;

/**
* WordWarZ/InvalidCredentialsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/frances/2025-9444-team6_finproject_java/src/GameService.idl
* Monday, May 5, 2025 10:08:28 PM CST
*/

public final class InvalidCredentialsHolder implements org.omg.CORBA.portable.Streamable
{
  public WordWarZ.InvalidCredentials value = null;

  public InvalidCredentialsHolder ()
  {
  }

  public InvalidCredentialsHolder (WordWarZ.InvalidCredentials initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordWarZ.InvalidCredentialsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordWarZ.InvalidCredentialsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordWarZ.InvalidCredentialsHelper.type ();
  }

}
