package WordWarZ;


/**
* WordWarZ/InvalidCredentials.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordWarZ.idl
* Saturday, April 26, 2025 8:20:14 AM SGT
*/

public final class InvalidCredentials extends org.omg.CORBA.UserException
{

  public InvalidCredentials ()
  {
    super(InvalidCredentialsHelper.id());
  } // ctor


  public InvalidCredentials (String $reason)
  {
    super(InvalidCredentialsHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidCredentials
