package WordWarZ;


/**
* WordWarZ/InvalidCredentials.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordWarZ.idl
* Monday, April 28, 2025 12:29:30 AM SGT
*/

public final class InvalidCredentials extends org.omg.CORBA.UserException
{
  public String reason = null;

  public InvalidCredentials ()
  {
    super(InvalidCredentialsHelper.id());
  }

  public InvalidCredentials (String _reason)
  {
    super(InvalidCredentialsHelper.id() + " " + _reason); // Combine ID with reason
    reason = _reason;
  }

  public InvalidCredentials (String $reason, String _reason)
  {
    super(InvalidCredentialsHelper.id() + " " + $reason + " " + _reason);
    reason = _reason;
  }

  @Override
  public String toString() {
    return reason != null ? reason : super.toString();
  }
}
