package WordWarZ;


/**
* WordWarZ/LoginPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Thursday, May 15, 2025 2:57:41 PM SGT
*/

public abstract class LoginPOA extends org.omg.PortableServer.Servant
 implements WordWarZ.LoginOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("authenticate", new java.lang.Integer (0));
    _methods.put ("logout", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // authentication
       case 0:  // WordWarZ/Login/authenticate
       {
         try {
           String username = in.read_string ();
           String password = in.read_string ();
           String $result = null;
           $result = this.authenticate (username, password);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (WordWarZ.InvalidCredentials $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.InvalidCredentialsHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // WordWarZ/Login/logout
       {
         try {
           String token = in.read_string ();
           this.logout (token);
           out = $rh.createReply();
         } catch (WordWarZ.NotLoggedIn $ex) {
           out = $rh.createExceptionReply ();
           WordWarZ.NotLoggedInHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:WordWarZ/Login:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Login _this() 
  {
    return LoginHelper.narrow(
    super._this_object());
  }

  public Login _this(org.omg.CORBA.ORB orb) 
  {
    return LoginHelper.narrow(
    super._this_object(orb));
  }


} // class LoginPOA
