package WordWarZ;

/**
* WordWarZ/LoginHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/frances/2025-9444-team6_finproject_java/WordWarZ.idl
* Saturday, May 3, 2025 8:13:31 AM CST
*/

public final class LoginHolder implements org.omg.CORBA.portable.Streamable
{
  public WordWarZ.Login value = null;

  public LoginHolder ()
  {
  }

  public LoginHolder (WordWarZ.Login initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordWarZ.LoginHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordWarZ.LoginHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordWarZ.LoginHelper.type ();
  }

}
