package WordWarZ;


/**
* WordWarZ/LoginOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Monday, May 12, 2025 7:37:02 PM SGT
*/

public interface LoginOperations 
{

  // authentication
  String authenticate (String username, String password) throws WordWarZ.InvalidCredentials;
  void logout (String token) throws WordWarZ.NotLoggedIn;
} // interface LoginOperations
