package WordWarZ;


/**
* WordWarZ/LoginOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordWarZ.idl
* Monday, April 28, 2025 12:29:30 AM SGT
*/

public interface LoginOperations 
{

  // authentication
  String login (String username, String password) throws WordWarZ.InvalidCredentials;
  void logout (String token) throws WordWarZ.NotLoggedIn;
} // interface LoginOperations
