package WordWarZ;


/**
* WordWarZ/LoginOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/frances/2025-9444-team6_finproject_java/src/GameService.idl
* Monday, May 5, 2025 10:08:28 PM CST
*/

public interface LoginOperations 
{

  // authentication
  String login (String username, String password) throws WordWarZ.InvalidCredentials;
  void logout (String token) throws WordWarZ.NotLoggedIn;
} // interface LoginOperations
