package WordWarZ;


/**
* WordWarZ/Login.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Wednesday, May 7, 2025 10:18:30 AM SGT
*/

public interface Login extends LoginOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Login
