package WordWarZ;

/**
* WordWarZ/NoOpponentFoundHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Wednesday, May 7, 2025 12:32:30 AM SGT
*/

public final class NoOpponentFoundHolder implements org.omg.CORBA.portable.Streamable
{
  public WordWarZ.NoOpponentFound value = null;

  public NoOpponentFoundHolder ()
  {
  }

  public NoOpponentFoundHolder (WordWarZ.NoOpponentFound initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordWarZ.NoOpponentFoundHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordWarZ.NoOpponentFoundHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordWarZ.NoOpponentFoundHelper.type ();
  }

}
