package WordWarZ;


/**
* WordWarZ/NoOpponentFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordWarZ.idl
* Saturday, April 26, 2025 8:20:14 AM SGT
*/

public final class NoOpponentFound extends org.omg.CORBA.UserException
{

  public NoOpponentFound ()
  {
    super(NoOpponentFoundHelper.id());
  } // ctor


  public NoOpponentFound (String $reason)
  {
    super(NoOpponentFoundHelper.id() + "  " + $reason);
  } // ctor

} // class NoOpponentFound
