package WordWarZ;


/**
* WordWarZ/NoOpponentFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/frances/2025-9444-team6_finproject_java/src/GameService.idl
* Monday, May 5, 2025 10:08:28 PM CST
*/

public final class NoOpponentFound extends org.omg.CORBA.UserException
{
  public String reason = null;

  public NoOpponentFound ()
  {
    super(NoOpponentFoundHelper.id());
  } // ctor

  public NoOpponentFound (String _reason)
  {
    super(NoOpponentFoundHelper.id());
    reason = _reason;
  } // ctor


  public NoOpponentFound (String $reason, String _reason)
  {
    super(NoOpponentFoundHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class NoOpponentFound
