package WordWarZ;

/**
* WordWarZ/NotInGameHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/frances/2025-9444-team6_finproject_java/src/GameService.idl
* Monday, May 5, 2025 10:08:28 PM CST
*/

public final class NotInGameHolder implements org.omg.CORBA.portable.Streamable
{
  public WordWarZ.NotInGame value = null;

  public NotInGameHolder ()
  {
  }

  public NotInGameHolder (WordWarZ.NotInGame initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordWarZ.NotInGameHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordWarZ.NotInGameHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordWarZ.NotInGameHelper.type ();
  }

}
