package WordWarZ;


/**
* WordWarZ/NotInGame.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/2025-9444-team6_finproject_java/src/util/idl/WordWarZ.idl
* Saturday, May 3, 2025 10:13:03 AM CST
*/

public final class NotInGame extends org.omg.CORBA.UserException
{
  public String reason = null;

  public NotInGame ()
  {
    super(NotInGameHelper.id());
  } // ctor

  public NotInGame (String _reason)
  {
    super(NotInGameHelper.id());
    reason = _reason;
  } // ctor


  public NotInGame (String $reason, String _reason)
  {
    super(NotInGameHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class NotInGame
