package WordWarZ;

/**
* WordWarZ/NotInGameHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordWarZ.idl
* Monday, April 28, 2025 12:29:30 AM SGT
*/

public final class NotInGameHolder implements org.omg.CORBA.portable.Streamable
{
  public WordWarZ.NotInGame value = null;

  public NotInGameHolder ()
  {
  }

  public NotInGameHolder (WordWarZ.NotInGame initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordWarZ.NotInGameHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordWarZ.NotInGameHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordWarZ.NotInGameHelper.type ();
  }

}
