package WordWarZ;


/**
* WordWarZ/NotInGame.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Sunday, May 11, 2025 5:49:02 PM SGT
*/

public final class NotInGame extends org.omg.CORBA.UserException
{
  public String reason = null;

  public NotInGame ()
  {
    super(NotInGameHelper.id());
  } // ctor

  public NotInGame (String _reason)
  {
    super(NotInGameHelper.id());
    reason = _reason;
  } // ctor


  public NotInGame (String $reason, String _reason)
  {
    super(NotInGameHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class NotInGame
