package WordWarZ;


/**
* WordWarZ/NotLoggedIn.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordWarZ.idl
* Wednesday, April 23, 2025 8:37:42 PM SGT
*/

public final class NotLoggedIn extends org.omg.CORBA.UserException
{

  public NotLoggedIn ()
  {
    super(NotLoggedInHelper.id());
  } // ctor


  public NotLoggedIn (String $reason)
  {
    super(NotLoggedInHelper.id() + "  " + $reason);
  } // ctor

} // class NotLoggedIn
