package WordWarZ;

/**
* WordWarZ/NotLoggedInHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordWarZ.idl
* Monday, April 28, 2025 12:29:30 AM SGT
*/

public final class NotLoggedInHolder implements org.omg.CORBA.portable.Streamable
{
  public WordWarZ.NotLoggedIn value = null;

  public NotLoggedInHolder ()
  {
  }

  public NotLoggedInHolder (WordWarZ.NotLoggedIn initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordWarZ.NotLoggedInHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordWarZ.NotLoggedInHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordWarZ.NotLoggedInHelper.type ();
  }

}
