package WordWarZ;


/**
* WordWarZ/NotLoggedIn.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/frances/2025-9444-team6_finproject_java/WordWarZ.idl
* Saturday, May 3, 2025 8:13:31 AM CST
*/

public final class NotLoggedIn extends org.omg.CORBA.UserException
{
  public String reason = null;

  public NotLoggedIn ()
  {
    super(NotLoggedInHelper.id());
  } // ctor

  public NotLoggedIn (String _reason)
  {
    super(NotLoggedInHelper.id());
    reason = _reason;
  } // ctor


  public NotLoggedIn (String $reason, String _reason)
  {
    super(NotLoggedInHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class NotLoggedIn
