package WordWarZ;


/**
* WordWarZ/NotLoggedIn.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Thursday, May 15, 2025 2:57:41 PM SGT
*/

public final class NotLoggedIn extends org.omg.CORBA.UserException
{
  public String reason = null;

  public NotLoggedIn ()
  {
    super(NotLoggedInHelper.id());
  } // ctor

  public NotLoggedIn (String _reason)
  {
    super(NotLoggedInHelper.id());
    reason = _reason;
  } // ctor


  public NotLoggedIn (String $reason, String _reason)
  {
    super(NotLoggedInHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class NotLoggedIn
