package WordWarZ;


/**
* WordWarZ/PlayerNotFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordWarZ.idl
* Saturday, April 26, 2025 8:20:14 AM SGT
*/

public final class PlayerNotFound extends org.omg.CORBA.UserException
{

  public PlayerNotFound ()
  {
    super(PlayerNotFoundHelper.id());
  } // ctor


  public PlayerNotFound (String $reason)
  {
    super(PlayerNotFoundHelper.id() + "  " + $reason);
  } // ctor

} // class PlayerNotFound
