package WordWarZ;

/**
* WordWarZ/PlayerNotInQueueHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/frances/2025-9444-team6_finproject_java/src/GameService.idl
* Monday, May 5, 2025 10:08:28 PM CST
*/

public final class PlayerNotInQueueHolder implements org.omg.CORBA.portable.Streamable
{
  public WordWarZ.PlayerNotInQueue value = null;

  public PlayerNotInQueueHolder ()
  {
  }

  public PlayerNotInQueueHolder (WordWarZ.PlayerNotInQueue initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordWarZ.PlayerNotInQueueHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordWarZ.PlayerNotInQueueHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordWarZ.PlayerNotInQueueHelper.type ();
  }

}
