package WordWarZ;

/**
* WordWarZ/PlayerCurrentlyLoggedInHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/frances/2025-9444-team6_finproject_java/src/AdminService.idl
* Monday, May 5, 2025 10:08:46 PM CST
*/

public final class PlayerCurrentlyLoggedInHolder implements org.omg.CORBA.portable.Streamable
{
  public WordWarZ.PlayerCurrentlyLoggedIn value = null;

  public PlayerCurrentlyLoggedInHolder ()
  {
  }

  public PlayerCurrentlyLoggedInHolder (WordWarZ.PlayerCurrentlyLoggedIn initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordWarZ.PlayerCurrentlyLoggedInHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordWarZ.PlayerCurrentlyLoggedInHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordWarZ.PlayerCurrentlyLoggedInHelper.type ();
  }

}
