package WordWarZ;

/**
* WordWarZ/PlayerNotFoundHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/2025-9444-team6_finproject_java/src/util/idl/WordWarZ.idl
* Saturday, May 3, 2025 10:13:03 AM CST
*/

public final class PlayerNotFoundHolder implements org.omg.CORBA.portable.Streamable
{
  public WordWarZ.PlayerNotFound value = null;

  public PlayerNotFoundHolder ()
  {
  }

  public PlayerNotFoundHolder (WordWarZ.PlayerNotFound initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordWarZ.PlayerNotFoundHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordWarZ.PlayerNotFoundHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordWarZ.PlayerNotFoundHelper.type ();
  }

}
