package WordWarZ;


/**
* WordWarZ/PlayerNotFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordWarZ.idl
* Monday, April 28, 2025 12:29:30 AM SGT
*/

public final class PlayerNotFound extends org.omg.CORBA.UserException
{
  public String reason = null;

  public PlayerNotFound ()
  {
    super(PlayerNotFoundHelper.id());
  } // ctor

  public PlayerNotFound (String _reason)
  {
    super(PlayerNotFoundHelper.id());
    reason = _reason;
  } // ctor


  public PlayerNotFound (String $reason, String _reason)
  {
    super(PlayerNotFoundHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class PlayerNotFound
