package WordWarZ;


/**
* WordWarZ/PlayerCurrentlyLoggedIn.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminService.idl
* Monday, May 5, 2025 10:03:06 PM SGT
*/

public final class PlayerCurrentlyLoggedIn extends org.omg.CORBA.UserException
{
  public String reason = null;

  public PlayerCurrentlyLoggedIn ()
  {
    super(PlayerCurrentlyLoggedInHelper.id());
  } // ctor

  public PlayerCurrentlyLoggedIn (String _reason)
  {
    super(PlayerCurrentlyLoggedInHelper.id());
    reason = _reason;
  } // ctor


  public PlayerCurrentlyLoggedIn (String $reason, String _reason)
  {
    super(PlayerCurrentlyLoggedInHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class PlayerCurrentlyLoggedIn
