package WordWarZ;


/**
* WordWarZ/PlayerNotInQueue.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/2025-9444-team6_finproject_java/src/util/idl/WordWarZ.idl
* Saturday, May 3, 2025 10:13:03 AM CST
*/

public final class PlayerNotInQueue extends org.omg.CORBA.UserException
{
  public String reason = null;

  public PlayerNotInQueue ()
  {
    super(PlayerNotInQueueHelper.id());
  } // ctor

  public PlayerNotInQueue (String _reason)
  {
    super(PlayerNotInQueueHelper.id());
    reason = _reason;
  } // ctor


  public PlayerNotInQueue (String $reason, String _reason)
  {
    super(PlayerNotInQueueHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class PlayerNotInQueue
