package WordWarZ;


/**
* WordWarZ/Player.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordWarZ.idl
* Monday, April 28, 2025 12:29:30 AM SGT
*/

public final class Player implements org.omg.CORBA.portable.IDLEntity
{
  public String username = null;
  public int wins = (int)0;

  public Player ()
  {
  } // ctor

  public Player (String _username, int _wins)
  {
    username = _username;
    wins = _wins;
  } // ctor

} // class Player
