package WordWarZ;


/**
* WordWarZ/Player.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/frances/2025-9444-team6_finproject_java/WordWarZ.idl
* Saturday, May 3, 2025 8:13:31 AM CST
*/

public final class Player implements org.omg.CORBA.portable.IDLEntity
{
  public String username = null;
  public int wins = (int)0;

  public Player ()
  {
  } // ctor

  public Player (String _username, int _wins)
  {
    username = _username;
    wins = _wins;
  } // ctor

} // class Player
