package WordWarZ;

/**
* WordWarZ/PlayerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Monday, May 12, 2025 2:34:56 AM SGT
*/

public final class PlayerHolder implements org.omg.CORBA.portable.Streamable
{
  public WordWarZ.Player value = null;

  public PlayerHolder ()
  {
  }

  public PlayerHolder (WordWarZ.Player initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordWarZ.PlayerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordWarZ.PlayerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordWarZ.PlayerHelper.type ();
  }

}
