package WordWarZ;


/**
* WordWarZ/PlayerNotInQueue.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordWarZ.idl
* Saturday, April 26, 2025 8:20:14 AM SGT
*/

public final class PlayerNotInQueue extends org.omg.CORBA.UserException
{

  public PlayerNotInQueue ()
  {
    super(PlayerNotInQueueHelper.id());
  } // ctor


  public PlayerNotInQueue (String $reason)
  {
    super(PlayerNotInQueueHelper.id() + "  " + $reason);
  } // ctor

} // class PlayerNotInQueue
