package WordWarZ;


/**
* WordWarZ/PlayerCurrentlyLoggedIn.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordWarZ.idl
* Saturday, April 26, 2025 8:20:14 AM SGT
*/

public final class PlayerCurrentlyLoggedIn extends org.omg.CORBA.UserException
{

  public PlayerCurrentlyLoggedIn ()
  {
    super(PlayerCurrentlyLoggedInHelper.id());
  } // ctor


  public PlayerCurrentlyLoggedIn (String $reason)
  {
    super(PlayerCurrentlyLoggedInHelper.id() + "  " + $reason);
  } // ctor

} // class PlayerCurrentlyLoggedIn
