package WordWarZ;


/**
* WordWarZ/RoundNotFinished.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Thursday, May 15, 2025 2:57:41 PM SGT
*/

public final class RoundNotFinished extends org.omg.CORBA.UserException
{
  public String reason = null;

  public RoundNotFinished ()
  {
    super(RoundNotFinishedHelper.id());
  } // ctor

  public RoundNotFinished (String _reason)
  {
    super(RoundNotFinishedHelper.id());
    reason = _reason;
  } // ctor


  public RoundNotFinished (String $reason, String _reason)
  {
    super(RoundNotFinishedHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class RoundNotFinished
