package WordWarZ;

/**
* WordWarZ/RoundNotFinishedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/frances/2025-9444-team6_finproject_java/src/GameService.idl
* Monday, May 5, 2025 10:08:28 PM CST
*/

public final class RoundNotFinishedHolder implements org.omg.CORBA.portable.Streamable
{
  public WordWarZ.RoundNotFinished value = null;

  public RoundNotFinishedHolder ()
  {
  }

  public RoundNotFinishedHolder (WordWarZ.RoundNotFinished initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordWarZ.RoundNotFinishedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordWarZ.RoundNotFinishedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordWarZ.RoundNotFinishedHelper.type ();
  }

}
