package WordWarZ;


/**
* WordWarZ/RoundNotFinished.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordWarZ.idl
* Saturday, April 26, 2025 8:20:14 AM SGT
*/

public final class RoundNotFinished extends org.omg.CORBA.UserException
{

  public RoundNotFinished ()
  {
    super(RoundNotFinishedHelper.id());
  } // ctor


  public RoundNotFinished (String $reason)
  {
    super(RoundNotFinishedHelper.id() + "  " + $reason);
  } // ctor

} // class RoundNotFinished
