package WordWarZ;


/**
* WordWarZ/RoundNotFinished.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/2025-9444-team6_finproject_java/src/util/idl/WordWarZ.idl
* Saturday, May 3, 2025 10:13:03 AM CST
*/

public final class RoundNotFinished extends org.omg.CORBA.UserException
{
  public String reason = null;

  public RoundNotFinished ()
  {
    super(RoundNotFinishedHelper.id());
  } // ctor

  public RoundNotFinished (String _reason)
  {
    super(RoundNotFinishedHelper.id());
    reason = _reason;
  } // ctor


  public RoundNotFinished (String $reason, String _reason)
  {
    super(RoundNotFinishedHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class RoundNotFinished
