package WordWarZ;


/**
* WordWarZ/UsernameAlreadyExists.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordWarZ.idl
* Monday, April 28, 2025 12:29:30 AM SGT
*/

public final class UsernameAlreadyExists extends org.omg.CORBA.UserException
{
  public String reason = null;

  public UsernameAlreadyExists ()
  {
    super(UsernameAlreadyExistsHelper.id());
  } // ctor

  public UsernameAlreadyExists (String _reason)
  {
    super(UsernameAlreadyExistsHelper.id());
    reason = _reason;
  } // ctor


  public UsernameAlreadyExists (String $reason, String _reason)
  {
    super(UsernameAlreadyExistsHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class UsernameAlreadyExists
