package WordWarZ;


/**
* WordWarZ/UsernameAlreadyExists.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordWarZ.idl
* Saturday, April 26, 2025 8:20:14 AM SGT
*/

public final class UsernameAlreadyExists extends org.omg.CORBA.UserException
{

  public UsernameAlreadyExists ()
  {
    super(UsernameAlreadyExistsHelper.id());
  } // ctor


  public UsernameAlreadyExists (String $reason)
  {
    super(UsernameAlreadyExistsHelper.id() + "  " + $reason);
  } // ctor

} // class UsernameAlreadyExists
