package WordWarZ;

/**
* WordWarZ/UsernameAlreadyExistsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordWarZ.idl
* Wednesday, April 23, 2025 8:37:42 PM SGT
*/

public final class UsernameAlreadyExistsHolder implements org.omg.CORBA.portable.Streamable
{
  public WordWarZ.UsernameAlreadyExists value = null;

  public UsernameAlreadyExistsHolder ()
  {
  }

  public UsernameAlreadyExistsHolder (WordWarZ.UsernameAlreadyExists initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordWarZ.UsernameAlreadyExistsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordWarZ.UsernameAlreadyExistsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordWarZ.UsernameAlreadyExistsHelper.type ();
  }

}
